spring:
  #  session:
  #    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#logging:
#  level:
#    com.baomidou.example.mapzper: debug
#    com.inzone.mall: info
#    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: input
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
